application: hungrywolverines
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: server.app

libraries:
#fix for import twitter error
  - name: ssl
    version: latest