application: hungrywolverines
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: server.app

libraries:
# - name: Flask
#   version: "0.10.1"
# - name: SQLAlchemy
#   version: "0.7.9"
# - name: twilio
#   version: "3.6.6"
# - python-twitter